name: Update Star Pravah HD Playlist

on:
  schedule:
    - cron: "*/15 * * * *"   # runs every 15 minutes
  workflow_dispatch:          # allows manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run update script
        run: node update.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add star_pravah_hd.m3u8
          git commit -m "Auto-update Star Pravah HD playlist" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
